services:
    dbhost:
      image: quanticschoolofbusiness/103mysql
    app:
      build: app/.
      ports: 
        - 3006:3006
      depends_on:
        - dbhost
        - redis-server
    redis-server:
      image: redis
    email:
      build: email/.
      ports: 
        - 25:25
      depends_on:
        - redis-server
      environment:
        TO_ADDRESS: ${TO_ADDRESS}
        FROM_ADDRESS: ${FROM_ADDRESS}
        FROM_PASSWORD: ${FROM_PASSWORD}