name: AllergyLab CI/CD
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Build images
              run: |
                    cd Part7a
                    docker build -t ${{ secrets.ISAAC16 }}/al-app:latest ./app
                    docker build -t ${{ secrets.ISAAC16 }}/al-db-loader:latest ./db-loader
                    docker build -t ${{ secrets.ISAAC16 }}/al-email:latest ./email


